// <auto-generated />
using System;
using CarePlus.MindfulnessAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarePlus.MindfulnessAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508031718_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarePlus.MindfulnessAPI.Models.Entities.MeditationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Concluida")
                        .HasColumnType("boolean")
                        .HasColumnName("concluida");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_minutos");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<DateTime>("RealizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("realizada_em");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("meditation_sessions");
                });

            modelBuilder.Entity("CarePlus.MindfulnessAPI.Models.Entities.MoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("NivelHumor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel_humor");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("mood_entries");
                });

            modelBuilder.Entity("CarePlus.MindfulnessAPI.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            AtualizadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataNascimento = new DateOnly(1990, 5, 15),
                            Email = "maria.silva@careplus.com",
                            Nome = "Maria Silva"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8901-bcde-f12345678901"),
                            AtualizadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataNascimento = new DateOnly(1985, 8, 22),
                            Email = "joao.santos@careplus.com",
                            Nome = "João Santos"
                        });
                });

            modelBuilder.Entity("CarePlus.MindfulnessAPI.Models.Entities.WellnessContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int?>("DuracaoEstimadaMin")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_estimada_min");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlRecurso")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_recurso");

                    b.HasKey("Id");

                    b.ToTable("wellness_contents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9012-cdef-123456789012"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "Artigo",
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Aprenda os fundamentos da meditação mindfulness e como ela pode melhorar sua saúde mental e bem-estar diário.",
                            DuracaoEstimadaMin = 10,
                            Titulo = "Introdução à Meditação Mindfulness"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0123-defa-234567890123"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "Exercicio",
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Técnica de respiração comprovada para reduzir ansiedade: inspire por 4 segundos, segure por 7, expire por 8.",
                            DuracaoEstimadaMin = 5,
                            Titulo = "Respiração 4-7-8 para Ansiedade"
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-1234-efab-345678901234"),
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Categoria = "Dica",
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Rotinas e hábitos simples que podem transformar a qualidade do seu sono e impactar positivamente sua saúde mental.",
                            DuracaoEstimadaMin = 7,
                            Titulo = "5 Dicas para Melhorar o Sono"
                        });
                });

            modelBuilder.Entity("CarePlus.MindfulnessAPI.Models.Entities.MeditationSession", b =>
                {
                    b.HasOne("CarePlus.MindfulnessAPI.Models.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarePlus.MindfulnessAPI.Models.Entities.MoodEntry", b =>
                {
                    b.HasOne("CarePlus.MindfulnessAPI.Models.Entities.User", "User")
                        .WithMany("MoodEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarePlus.MindfulnessAPI.Models.Entities.User", b =>
                {
                    b.Navigation("MoodEntries");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
